server:
  port: 8080

spring:
  application:
    name: spark-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spark_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  redis:
    key-pre: ${spring.application.name}:auth

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印 SQL 日志
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 1810000  # 1800000 30 minutes (in ms)
  refresh-expiration: 604800000 # 7 days (in ms)

bloom-filter:
  expected-insertions: 1000
  false-probability: 0.01

logging:
  level:
    com.spark.security: debug
